version: '3'

services:

  fusionauth:
    environment:
      FUSIONAUTH_APP_URL: https://${HOSTNAME}

  nginx:
    image: nginx:1.19.2
    # wait for fusionauth container or else nginx will fail to resolve upstream resources
    depends_on:
      - fusionauth
    networks:
      - db
    restart: unless-stopped
    volumes:
      - ./http_default.conf:/etc/nginx/conf.d/http_default.conf
      - letsencrypt:/etc/letsencrypt
      - certbot_www:./data/certbot
    ports:
      - 80:80

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_www:./data/certbot

volumes:
  letsencrypt:
  certbot_www:
